//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Bekap4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Контрагенты.
    /// </summary>
    // *** Start programmer edit section *** (Контрагенты CustomAttributes)

    // *** End programmer edit section *** (Контрагенты CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КонтрагентыE", new string[] {
            "Контрагент as \'Контрагент\'"})]
    [View("КонтрагентыL", new string[] {
            "Контрагент as \'Контрагент\'"})]
    public class Контрагенты : ICSSoft.STORMNET.DataObject
    {
        
        private string fКонтрагент;
        
        private IIS.Bekap4.ЗаказПост fЗаказПост;
        
        // *** Start programmer edit section *** (Контрагенты CustomMembers)

        // *** End programmer edit section *** (Контрагенты CustomMembers)

        
        /// <summary>
        /// Контрагент.
        /// </summary>
        // *** Start programmer edit section *** (Контрагенты.Контрагент CustomAttributes)

        // *** End programmer edit section *** (Контрагенты.Контрагент CustomAttributes)
        [StrLen(255)]
        public virtual string Контрагент
        {
            get
            {
                // *** Start programmer edit section *** (Контрагенты.Контрагент Get start)

                // *** End programmer edit section *** (Контрагенты.Контрагент Get start)
                string result = this.fКонтрагент;
                // *** Start programmer edit section *** (Контрагенты.Контрагент Get end)

                // *** End programmer edit section *** (Контрагенты.Контрагент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контрагенты.Контрагент Set start)

                // *** End programmer edit section *** (Контрагенты.Контрагент Set start)
                this.fКонтрагент = value;
                // *** Start programmer edit section *** (Контрагенты.Контрагент Set end)

                // *** End programmer edit section *** (Контрагенты.Контрагент Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Bekap4.ЗаказПост.
        /// </summary>
        // *** Start programmer edit section *** (Контрагенты.ЗаказПост CustomAttributes)

        // *** End programmer edit section *** (Контрагенты.ЗаказПост CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ЗаказПост"})]
        public virtual IIS.Bekap4.ЗаказПост ЗаказПост
        {
            get
            {
                // *** Start programmer edit section *** (Контрагенты.ЗаказПост Get start)

                // *** End programmer edit section *** (Контрагенты.ЗаказПост Get start)
                IIS.Bekap4.ЗаказПост result = this.fЗаказПост;
                // *** Start programmer edit section *** (Контрагенты.ЗаказПост Get end)

                // *** End programmer edit section *** (Контрагенты.ЗаказПост Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контрагенты.ЗаказПост Set start)

                // *** End programmer edit section *** (Контрагенты.ЗаказПост Set start)
                this.fЗаказПост = value;
                // *** Start programmer edit section *** (Контрагенты.ЗаказПост Set end)

                // *** End programmer edit section *** (Контрагенты.ЗаказПост Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КонтрагентыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КонтрагентыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КонтрагентыE", typeof(IIS.Bekap4.Контрагенты));
                }
            }
            
            /// <summary>
            /// "КонтрагентыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КонтрагентыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КонтрагентыL", typeof(IIS.Bekap4.Контрагенты));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Контрагенты.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfКонтрагенты CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfКонтрагенты CustomAttributes)
    public class DetailArrayOfКонтрагенты : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Bekap4.DetailArrayOfКонтрагенты members)

        // *** End programmer edit section *** (IIS.Bekap4.DetailArrayOfКонтрагенты members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Контрагенты by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Контрагенты.
        /// </summary>
        public DetailArrayOfКонтрагенты(IIS.Bekap4.ЗаказПост fЗаказПост) : 
                base(typeof(Контрагенты), ((ICSSoft.STORMNET.DataObject)(fЗаказПост)))
        {
        }
        
        public IIS.Bekap4.Контрагенты this[int index]
        {
            get
            {
                return ((IIS.Bekap4.Контрагенты)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Bekap4.Контрагенты dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
