//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Bekap4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Организации.
    /// </summary>
    // *** Start programmer edit section *** (Организации CustomAttributes)

    // *** End programmer edit section *** (Организации CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОрганизацииE", new string[] {
            "Организация as \'Организация\'"})]
    public class Организации : ICSSoft.STORMNET.DataObject
    {
        
        private string fОрганизация;
        
        private IIS.Bekap4.ЗаказПост fЗаказПост;
        
        // *** Start programmer edit section *** (Организации CustomMembers)

        // *** End programmer edit section *** (Организации CustomMembers)

        
        /// <summary>
        /// Организация.
        /// </summary>
        // *** Start programmer edit section *** (Организации.Организация CustomAttributes)

        // *** End programmer edit section *** (Организации.Организация CustomAttributes)
        [StrLen(255)]
        public virtual string Организация
        {
            get
            {
                // *** Start programmer edit section *** (Организации.Организация Get start)

                // *** End programmer edit section *** (Организации.Организация Get start)
                string result = this.fОрганизация;
                // *** Start programmer edit section *** (Организации.Организация Get end)

                // *** End programmer edit section *** (Организации.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организации.Организация Set start)

                // *** End programmer edit section *** (Организации.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (Организации.Организация Set end)

                // *** End programmer edit section *** (Организации.Организация Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Bekap4.ЗаказПост.
        /// </summary>
        // *** Start programmer edit section *** (Организации.ЗаказПост CustomAttributes)

        // *** End programmer edit section *** (Организации.ЗаказПост CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ЗаказПост"})]
        public virtual IIS.Bekap4.ЗаказПост ЗаказПост
        {
            get
            {
                // *** Start programmer edit section *** (Организации.ЗаказПост Get start)

                // *** End programmer edit section *** (Организации.ЗаказПост Get start)
                IIS.Bekap4.ЗаказПост result = this.fЗаказПост;
                // *** Start programmer edit section *** (Организации.ЗаказПост Get end)

                // *** End programmer edit section *** (Организации.ЗаказПост Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организации.ЗаказПост Set start)

                // *** End programmer edit section *** (Организации.ЗаказПост Set start)
                this.fЗаказПост = value;
                // *** Start programmer edit section *** (Организации.ЗаказПост Set end)

                // *** End programmer edit section *** (Организации.ЗаказПост Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОрганизацииE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОрганизацииE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОрганизацииE", typeof(IIS.Bekap4.Организации));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Организации.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfОрганизации CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfОрганизации CustomAttributes)
    public class DetailArrayOfОрганизации : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Bekap4.DetailArrayOfОрганизации members)

        // *** End programmer edit section *** (IIS.Bekap4.DetailArrayOfОрганизации members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Организации by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Организации.
        /// </summary>
        public DetailArrayOfОрганизации(IIS.Bekap4.ЗаказПост fЗаказПост) : 
                base(typeof(Организации), ((ICSSoft.STORMNET.DataObject)(fЗаказПост)))
        {
        }
        
        public IIS.Bekap4.Организации this[int index]
        {
            get
            {
                return ((IIS.Bekap4.Организации)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Bekap4.Организации dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
